### ISSUE TITLE
single_prediction error

### ISSUE THREAD

**Issue by GaodengLi** [Fenglei104/DeepPROTACs#9]
Great Job!  but when I run this command for prediction
```bash
python single_prediction.py single_test/
```
I encounter a error like this:
```bash
AttributeError: 'GCNConv' object has no attribute '_explain'
``` 
I think it may be something wrong with the torch_geometric, such as the version, but my conda environment was created according to your supplied `env.yaml`.
Another question,is the model named `test.pt` you supplied in this repositories genearted by running the commad:
```bash
python main.py
```
I running the command, a model was generated, but I have compared the `test.pt` model with mine,  they are different.
The processed feature under the folder `data` just a toy dataset, yes?
Looking forward to your reply!
Best Regrads.

**Comment by Fenglei104** [comment]
Hi, thanks for your feedback.

I met the same problem of the `torch geometric` version some days ago, but it was in Windows and with no GPUs, while I prepared the `yaml` file in Ubuntu 18.04 with an RTX 3090. So it might be the same question. You can try the following versions:
```
pytorch=1.8.1=py3.7_cpu_0
torch-geometric==2.0.0
torch-scatter==2.0.9
torch-sparse==0.6.12
```

The `test.pt` is trained with the data described in the paper, while here we only provide 3 examples. And I'm really sorry that the data is in use and I can not publish it now.

**Comment by GaodengLi** [comment]
Thanks for your reply, I changed the version of `torch-geometric` from 2.0.4 to 2.0.0, the problem was solved.
Best Regrads.
